language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "cn-src"
    token:
      secure: "fj0mUfnY0yKjXsO0g52XXOouPUFWcox+WDB0qd9Qc3STvoqu4T4kV2Udw79OGm543j0Z6syrDTy946irdUnK+Y2mGGd1Mjfb3UnGWXfQpkFyUTabv9LHji+dFbf7oTitatsKe+y6unROuzu1MDGzPXUaSYCqG9RguDo7YGusa1CTFKu5zmp5SugxrZzRLcYBdQtj/k2x1rKkd+pMehYH9XFxOqrtY9g61eyL1NmuQAaYX9heJFQV4QunrzpEbVBx3F3fOLdVxoZH033bAVQA0H38q5iAqHvOnkY8QI1ab2arFfMlBwju5alonGt0x2j61UG3XlapARKRjOxYrl/cr2b9fEDUmO95ABI54nnw8Pc7J5z6A0tTA4oH2OzorTTgORgjtaRHmmyE9kAfBmx9K19sfpqAnfvKrkKKfM8Q31aP+6i3IYQ1o/dVATEvqqzZz0oTsXK8ZnSwg0z3HMwe8yWeJsvVY5UlsnbLsoCyd+CEqCpEQoVwJMQiQE38rEPEH+HmNCzY2RVq+pMJvjoYEsS0LwKB+W46ChurMiT2AZTf16hPvwurMzsNhGGyzpZ52Y7AwpR+Nz87ql6YcsNh9S1exmdJPQ3aJwbhv+cAqkoGLIXOBcmtxYWu1aUY5wiCDaziCKbhfGhdKDn+eHcBa2msmq+LyYHDhB04ETObzho="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
  