language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "cn-src-github"
    token:
      secure: "SVLypsWutQs7zOXVF9wZKWun6HMu9/jhffzdWGTpwj9PaAxRJ2urwyMHWXtmdLZDIngnLndebd97O/PvzHFd0sNxqyuRdhCpJ9+0/XIvudA+z66GJCH+VtQ7XAEEcvPywtfSFaUgZPkpkrP/Je1CJ7Eolzwj1PILfIKwTnAzaGw8j5u8lYUQGsQ+Q2Xqg0vbvx84FpAoO0YSUOLtTlVl0z7uaGNICghHlOjUZDGuxdDuGXYt7UUS63otJCYf5qQivBaBgwTnRfKTd5XlLqvvU1HF4OQljv2FT3SAsfoP9sek91KmKhRmWnXZ0DW6+V38LrEmDVOvi+kch3UA47rP4HnNo1lbrXJAKvFrl6JSaCLVlhV1zxKRUUuPPISzg/qQ5DehRYiascJkbxUjRSauBKNyUJLRF2QUbKpQCfM+jvtLvqhxIEmHV6BMcb5JWt3uCKC0oVU6Ge5bXoZ7qsCKyGYapzN965gG1pFdgE365NUsKErQu2E+ijM437RBJaU7liXyri8pe6V3CGJB8mwTv5zMKb7lXFiYBbfg3IumR3LI/KoGfLJQr1fnsO14CuPOEQXZeoeYnSAYv7X2XCRTP6e/mBalgyhcXpSSducLVDCm0mzwVeMChBxKAGZw6JxlmFKSOCUGRtJOZc/Ol+NJse4T3yrZuF0i8ve2Ob+tDGU="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
  